#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeTa.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Bun")]
	public partial class BunContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBunBo(BunBo instance);
    partial void UpdateBunBo(BunBo instance);
    partial void DeleteBunBo(BunBo instance);
    partial void InsertManager(Manager instance);
    partial void UpdateManager(Manager instance);
    partial void DeleteManager(Manager instance);
    partial void InsertCHITIETDONTHANG(CHITIETDONTHANG instance);
    partial void UpdateCHITIETDONTHANG(CHITIETDONTHANG instance);
    partial void DeleteCHITIETDONTHANG(CHITIETDONTHANG instance);
    partial void InsertChitietmon(Chitietmon instance);
    partial void UpdateChitietmon(Chitietmon instance);
    partial void DeleteChitietmon(Chitietmon instance);
    partial void InsertDodungthem(Dodungthem instance);
    partial void UpdateDodungthem(Dodungthem instance);
    partial void DeleteDodungthem(Dodungthem instance);
    partial void InsertDONDATHANG(DONDATHANG instance);
    partial void UpdateDONDATHANG(DONDATHANG instance);
    partial void DeleteDONDATHANG(DONDATHANG instance);
    partial void InsertKH(KH instance);
    partial void UpdateKH(KH instance);
    partial void DeleteKH(KH instance);
    #endregion
		
		public BunContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BunConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BunContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BunContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BunContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BunContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BunBo> BunBos
		{
			get
			{
				return this.GetTable<BunBo>();
			}
		}
		
		public System.Data.Linq.Table<Manager> Managers
		{
			get
			{
				return this.GetTable<Manager>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETDONTHANG> CHITIETDONTHANGs
		{
			get
			{
				return this.GetTable<CHITIETDONTHANG>();
			}
		}
		
		public System.Data.Linq.Table<Chitietmon> Chitietmons
		{
			get
			{
				return this.GetTable<Chitietmon>();
			}
		}
		
		public System.Data.Linq.Table<Dodungthem> Dodungthems
		{
			get
			{
				return this.GetTable<Dodungthem>();
			}
		}
		
		public System.Data.Linq.Table<DONDATHANG> DONDATHANGs
		{
			get
			{
				return this.GetTable<DONDATHANG>();
			}
		}
		
		public System.Data.Linq.Table<KH> KHs
		{
			get
			{
				return this.GetTable<KH>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BunBo")]
	public partial class BunBo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mamon;
		
		private string _Tenmon;
		
		private decimal _GiaTien;
		
		private string _Tinhtrang;
		
		private string _Img;
		
		private string _Mota;
		
		private EntitySet<CHITIETDONTHANG> _CHITIETDONTHANGs;
		
		private EntityRef<Chitietmon> _Chitietmon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMamonChanging(int value);
    partial void OnMamonChanged();
    partial void OnTenmonChanging(string value);
    partial void OnTenmonChanged();
    partial void OnGiaTienChanging(decimal value);
    partial void OnGiaTienChanged();
    partial void OnTinhtrangChanging(string value);
    partial void OnTinhtrangChanged();
    partial void OnImgChanging(string value);
    partial void OnImgChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    #endregion
		
		public BunBo()
		{
			this._CHITIETDONTHANGs = new EntitySet<CHITIETDONTHANG>(new Action<CHITIETDONTHANG>(this.attach_CHITIETDONTHANGs), new Action<CHITIETDONTHANG>(this.detach_CHITIETDONTHANGs));
			this._Chitietmon = default(EntityRef<Chitietmon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mamon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mamon
		{
			get
			{
				return this._Mamon;
			}
			set
			{
				if ((this._Mamon != value))
				{
					this.OnMamonChanging(value);
					this.SendPropertyChanging();
					this._Mamon = value;
					this.SendPropertyChanged("Mamon");
					this.OnMamonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenmon", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Tenmon
		{
			get
			{
				return this._Tenmon;
			}
			set
			{
				if ((this._Tenmon != value))
				{
					this.OnTenmonChanging(value);
					this.SendPropertyChanging();
					this._Tenmon = value;
					this.SendPropertyChanged("Tenmon");
					this.OnTenmonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="Decimal(18,0) NOT NULL")]
		public decimal GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang", DbType="NVarChar(30)")]
		public string Tinhtrang
		{
			get
			{
				return this._Tinhtrang;
			}
			set
			{
				if ((this._Tinhtrang != value))
				{
					this.OnTinhtrangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang = value;
					this.SendPropertyChanged("Tinhtrang");
					this.OnTinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Img
		{
			get
			{
				return this._Img;
			}
			set
			{
				if ((this._Img != value))
				{
					this.OnImgChanging(value);
					this.SendPropertyChanging();
					this._Img = value;
					this.SendPropertyChanged("Img");
					this.OnImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(100)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BunBo_CHITIETDONTHANG", Storage="_CHITIETDONTHANGs", ThisKey="Mamon", OtherKey="Mamon")]
		public EntitySet<CHITIETDONTHANG> CHITIETDONTHANGs
		{
			get
			{
				return this._CHITIETDONTHANGs;
			}
			set
			{
				this._CHITIETDONTHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BunBo_Chitietmon", Storage="_Chitietmon", ThisKey="Mamon", OtherKey="Mamon", IsUnique=true, IsForeignKey=false)]
		public Chitietmon Chitietmon
		{
			get
			{
				return this._Chitietmon.Entity;
			}
			set
			{
				Chitietmon previousValue = this._Chitietmon.Entity;
				if (((previousValue != value) 
							|| (this._Chitietmon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Chitietmon.Entity = null;
						previousValue.BunBo = null;
					}
					this._Chitietmon.Entity = value;
					if ((value != null))
					{
						value.BunBo = this;
					}
					this.SendPropertyChanged("Chitietmon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONTHANGs(CHITIETDONTHANG entity)
		{
			this.SendPropertyChanging();
			entity.BunBo = this;
		}
		
		private void detach_CHITIETDONTHANGs(CHITIETDONTHANG entity)
		{
			this.SendPropertyChanging();
			entity.BunBo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Manager")]
	public partial class Manager : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDM;
		
		private string _HoTenM;
		
		private string _TaikhoanM;
		
		private string _MatkhauM;
		
		private string _EmailM;
		
		private string _DiachiM;
		
		private string _DienthoaiM;
		
		private System.Nullable<System.DateTime> _NgaysinhM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDMChanging(int value);
    partial void OnIDMChanged();
    partial void OnHoTenMChanging(string value);
    partial void OnHoTenMChanged();
    partial void OnTaikhoanMChanging(string value);
    partial void OnTaikhoanMChanged();
    partial void OnMatkhauMChanging(string value);
    partial void OnMatkhauMChanged();
    partial void OnEmailMChanging(string value);
    partial void OnEmailMChanged();
    partial void OnDiachiMChanging(string value);
    partial void OnDiachiMChanged();
    partial void OnDienthoaiMChanging(string value);
    partial void OnDienthoaiMChanged();
    partial void OnNgaysinhMChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhMChanged();
    #endregion
		
		public Manager()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDM
		{
			get
			{
				return this._IDM;
			}
			set
			{
				if ((this._IDM != value))
				{
					this.OnIDMChanging(value);
					this.SendPropertyChanging();
					this._IDM = value;
					this.SendPropertyChanged("IDM");
					this.OnIDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTenM
		{
			get
			{
				return this._HoTenM;
			}
			set
			{
				if ((this._HoTenM != value))
				{
					this.OnHoTenMChanging(value);
					this.SendPropertyChanging();
					this._HoTenM = value;
					this.SendPropertyChanged("HoTenM");
					this.OnHoTenMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaikhoanM", DbType="VarChar(50)")]
		public string TaikhoanM
		{
			get
			{
				return this._TaikhoanM;
			}
			set
			{
				if ((this._TaikhoanM != value))
				{
					this.OnTaikhoanMChanging(value);
					this.SendPropertyChanging();
					this._TaikhoanM = value;
					this.SendPropertyChanged("TaikhoanM");
					this.OnTaikhoanMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatkhauM", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatkhauM
		{
			get
			{
				return this._MatkhauM;
			}
			set
			{
				if ((this._MatkhauM != value))
				{
					this.OnMatkhauMChanging(value);
					this.SendPropertyChanging();
					this._MatkhauM = value;
					this.SendPropertyChanged("MatkhauM");
					this.OnMatkhauMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailM", DbType="VarChar(100)")]
		public string EmailM
		{
			get
			{
				return this._EmailM;
			}
			set
			{
				if ((this._EmailM != value))
				{
					this.OnEmailMChanging(value);
					this.SendPropertyChanging();
					this._EmailM = value;
					this.SendPropertyChanged("EmailM");
					this.OnEmailMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiachiM", DbType="NVarChar(100)")]
		public string DiachiM
		{
			get
			{
				return this._DiachiM;
			}
			set
			{
				if ((this._DiachiM != value))
				{
					this.OnDiachiMChanging(value);
					this.SendPropertyChanging();
					this._DiachiM = value;
					this.SendPropertyChanged("DiachiM");
					this.OnDiachiMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienthoaiM", DbType="VarChar(15)")]
		public string DienthoaiM
		{
			get
			{
				return this._DienthoaiM;
			}
			set
			{
				if ((this._DienthoaiM != value))
				{
					this.OnDienthoaiMChanging(value);
					this.SendPropertyChanging();
					this._DienthoaiM = value;
					this.SendPropertyChanged("DienthoaiM");
					this.OnDienthoaiMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaysinhM", DbType="Date")]
		public System.Nullable<System.DateTime> NgaysinhM
		{
			get
			{
				return this._NgaysinhM;
			}
			set
			{
				if ((this._NgaysinhM != value))
				{
					this.OnNgaysinhMChanging(value);
					this.SendPropertyChanging();
					this._NgaysinhM = value;
					this.SendPropertyChanged("NgaysinhM");
					this.OnNgaysinhMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDONTHANG")]
	public partial class CHITIETDONTHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonHang;
		
		private int _Mamon;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<decimal> _Dongia;
		
		private EntityRef<BunBo> _BunBo;
		
		private EntityRef<DONDATHANG> _DONDATHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonHangChanging(int value);
    partial void OnMaDonHangChanged();
    partial void OnMamonChanging(int value);
    partial void OnMamonChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnDongiaChanging(System.Nullable<decimal> value);
    partial void OnDongiaChanged();
    #endregion
		
		public CHITIETDONTHANG()
		{
			this._BunBo = default(EntityRef<BunBo>);
			this._DONDATHANG = default(EntityRef<DONDATHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					if (this._DONDATHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mamon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Mamon
		{
			get
			{
				return this._Mamon;
			}
			set
			{
				if ((this._Mamon != value))
				{
					if (this._BunBo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMamonChanging(value);
					this.SendPropertyChanging();
					this._Mamon = value;
					this.SendPropertyChanged("Mamon");
					this.OnMamonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BunBo_CHITIETDONTHANG", Storage="_BunBo", ThisKey="Mamon", OtherKey="Mamon", IsForeignKey=true)]
		public BunBo BunBo
		{
			get
			{
				return this._BunBo.Entity;
			}
			set
			{
				BunBo previousValue = this._BunBo.Entity;
				if (((previousValue != value) 
							|| (this._BunBo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BunBo.Entity = null;
						previousValue.CHITIETDONTHANGs.Remove(this);
					}
					this._BunBo.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONTHANGs.Add(this);
						this._Mamon = value.Mamon;
					}
					else
					{
						this._Mamon = default(int);
					}
					this.SendPropertyChanged("BunBo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONDATHANG_CHITIETDONTHANG", Storage="_DONDATHANG", ThisKey="MaDonHang", OtherKey="MaDonHang", IsForeignKey=true)]
		public DONDATHANG DONDATHANG
		{
			get
			{
				return this._DONDATHANG.Entity;
			}
			set
			{
				DONDATHANG previousValue = this._DONDATHANG.Entity;
				if (((previousValue != value) 
							|| (this._DONDATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONDATHANG.Entity = null;
						previousValue.CHITIETDONTHANGs.Remove(this);
					}
					this._DONDATHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONTHANGs.Add(this);
						this._MaDonHang = value.MaDonHang;
					}
					else
					{
						this._MaDonHang = default(int);
					}
					this.SendPropertyChanged("DONDATHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chitietmon")]
	public partial class Chitietmon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mamon;
		
		private System.Nullable<int> _Madodungthem;
		
		private System.Nullable<int> _Soluong;
		
		private EntityRef<BunBo> _BunBo;
		
		private EntityRef<Dodungthem> _Dodungthem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMamonChanging(int value);
    partial void OnMamonChanged();
    partial void OnMadodungthemChanging(System.Nullable<int> value);
    partial void OnMadodungthemChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    #endregion
		
		public Chitietmon()
		{
			this._BunBo = default(EntityRef<BunBo>);
			this._Dodungthem = default(EntityRef<Dodungthem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mamon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Mamon
		{
			get
			{
				return this._Mamon;
			}
			set
			{
				if ((this._Mamon != value))
				{
					if (this._BunBo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMamonChanging(value);
					this.SendPropertyChanging();
					this._Mamon = value;
					this.SendPropertyChanged("Mamon");
					this.OnMamonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madodungthem", DbType="Int")]
		public System.Nullable<int> Madodungthem
		{
			get
			{
				return this._Madodungthem;
			}
			set
			{
				if ((this._Madodungthem != value))
				{
					if (this._Dodungthem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMadodungthemChanging(value);
					this.SendPropertyChanging();
					this._Madodungthem = value;
					this.SendPropertyChanged("Madodungthem");
					this.OnMadodungthemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BunBo_Chitietmon", Storage="_BunBo", ThisKey="Mamon", OtherKey="Mamon", IsForeignKey=true)]
		public BunBo BunBo
		{
			get
			{
				return this._BunBo.Entity;
			}
			set
			{
				BunBo previousValue = this._BunBo.Entity;
				if (((previousValue != value) 
							|| (this._BunBo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BunBo.Entity = null;
						previousValue.Chitietmon = null;
					}
					this._BunBo.Entity = value;
					if ((value != null))
					{
						value.Chitietmon = this;
						this._Mamon = value.Mamon;
					}
					else
					{
						this._Mamon = default(int);
					}
					this.SendPropertyChanged("BunBo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dodungthem_Chitietmon", Storage="_Dodungthem", ThisKey="Madodungthem", OtherKey="Madodungthem", IsForeignKey=true)]
		public Dodungthem Dodungthem
		{
			get
			{
				return this._Dodungthem.Entity;
			}
			set
			{
				Dodungthem previousValue = this._Dodungthem.Entity;
				if (((previousValue != value) 
							|| (this._Dodungthem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dodungthem.Entity = null;
						previousValue.Chitietmons.Remove(this);
					}
					this._Dodungthem.Entity = value;
					if ((value != null))
					{
						value.Chitietmons.Add(this);
						this._Madodungthem = value.Madodungthem;
					}
					else
					{
						this._Madodungthem = default(Nullable<int>);
					}
					this.SendPropertyChanged("Dodungthem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dodungthem")]
	public partial class Dodungthem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Madodungthem;
		
		private string _Tendodung;
		
		private System.Nullable<decimal> _GiaTienDD;
		
		private System.Nullable<bool> _Hientrang;
		
		private string _Imgdd;
		
		private EntitySet<Chitietmon> _Chitietmons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMadodungthemChanging(int value);
    partial void OnMadodungthemChanged();
    partial void OnTendodungChanging(string value);
    partial void OnTendodungChanged();
    partial void OnGiaTienDDChanging(System.Nullable<decimal> value);
    partial void OnGiaTienDDChanged();
    partial void OnHientrangChanging(System.Nullable<bool> value);
    partial void OnHientrangChanged();
    partial void OnImgddChanging(string value);
    partial void OnImgddChanged();
    #endregion
		
		public Dodungthem()
		{
			this._Chitietmons = new EntitySet<Chitietmon>(new Action<Chitietmon>(this.attach_Chitietmons), new Action<Chitietmon>(this.detach_Chitietmons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madodungthem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Madodungthem
		{
			get
			{
				return this._Madodungthem;
			}
			set
			{
				if ((this._Madodungthem != value))
				{
					this.OnMadodungthemChanging(value);
					this.SendPropertyChanging();
					this._Madodungthem = value;
					this.SendPropertyChanged("Madodungthem");
					this.OnMadodungthemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tendodung", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Tendodung
		{
			get
			{
				return this._Tendodung;
			}
			set
			{
				if ((this._Tendodung != value))
				{
					this.OnTendodungChanging(value);
					this.SendPropertyChanging();
					this._Tendodung = value;
					this.SendPropertyChanged("Tendodung");
					this.OnTendodungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTienDD", DbType="Money")]
		public System.Nullable<decimal> GiaTienDD
		{
			get
			{
				return this._GiaTienDD;
			}
			set
			{
				if ((this._GiaTienDD != value))
				{
					this.OnGiaTienDDChanging(value);
					this.SendPropertyChanging();
					this._GiaTienDD = value;
					this.SendPropertyChanged("GiaTienDD");
					this.OnGiaTienDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hientrang", DbType="Bit")]
		public System.Nullable<bool> Hientrang
		{
			get
			{
				return this._Hientrang;
			}
			set
			{
				if ((this._Hientrang != value))
				{
					this.OnHientrangChanging(value);
					this.SendPropertyChanging();
					this._Hientrang = value;
					this.SendPropertyChanged("Hientrang");
					this.OnHientrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imgdd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Imgdd
		{
			get
			{
				return this._Imgdd;
			}
			set
			{
				if ((this._Imgdd != value))
				{
					this.OnImgddChanging(value);
					this.SendPropertyChanging();
					this._Imgdd = value;
					this.SendPropertyChanged("Imgdd");
					this.OnImgddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dodungthem_Chitietmon", Storage="_Chitietmons", ThisKey="Madodungthem", OtherKey="Madodungthem")]
		public EntitySet<Chitietmon> Chitietmons
		{
			get
			{
				return this._Chitietmons;
			}
			set
			{
				this._Chitietmons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Chitietmons(Chitietmon entity)
		{
			this.SendPropertyChanging();
			entity.Dodungthem = this;
		}
		
		private void detach_Chitietmons(Chitietmon entity)
		{
			this.SendPropertyChanging();
			entity.Dodungthem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONDATHANG")]
	public partial class DONDATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonHang;
		
		private System.Nullable<bool> _Dathanhtoan;
		
		private System.Nullable<bool> _Tinhtranggiaohang;
		
		private System.Nullable<System.DateTime> _Ngaydat;
		
		private System.Nullable<System.DateTime> _Ngaygiao;
		
		private System.Nullable<int> _IDKH;
		
		private System.Nullable<decimal> _Tongtien;
		
		private EntitySet<CHITIETDONTHANG> _CHITIETDONTHANGs;
		
		private EntityRef<KH> _KH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonHangChanging(int value);
    partial void OnMaDonHangChanged();
    partial void OnDathanhtoanChanging(System.Nullable<bool> value);
    partial void OnDathanhtoanChanged();
    partial void OnTinhtranggiaohangChanging(System.Nullable<bool> value);
    partial void OnTinhtranggiaohangChanged();
    partial void OnNgaydatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydatChanged();
    partial void OnNgaygiaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaygiaoChanged();
    partial void OnIDKHChanging(System.Nullable<int> value);
    partial void OnIDKHChanged();
    partial void OnTongtienChanging(System.Nullable<decimal> value);
    partial void OnTongtienChanged();
    #endregion
		
		public DONDATHANG()
		{
			this._CHITIETDONTHANGs = new EntitySet<CHITIETDONTHANG>(new Action<CHITIETDONTHANG>(this.attach_CHITIETDONTHANGs), new Action<CHITIETDONTHANG>(this.detach_CHITIETDONTHANGs));
			this._KH = default(EntityRef<KH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dathanhtoan", DbType="Bit")]
		public System.Nullable<bool> Dathanhtoan
		{
			get
			{
				return this._Dathanhtoan;
			}
			set
			{
				if ((this._Dathanhtoan != value))
				{
					this.OnDathanhtoanChanging(value);
					this.SendPropertyChanging();
					this._Dathanhtoan = value;
					this.SendPropertyChanged("Dathanhtoan");
					this.OnDathanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtranggiaohang", DbType="Bit")]
		public System.Nullable<bool> Tinhtranggiaohang
		{
			get
			{
				return this._Tinhtranggiaohang;
			}
			set
			{
				if ((this._Tinhtranggiaohang != value))
				{
					this.OnTinhtranggiaohangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtranggiaohang = value;
					this.SendPropertyChanged("Tinhtranggiaohang");
					this.OnTinhtranggiaohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydat", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydat
		{
			get
			{
				return this._Ngaydat;
			}
			set
			{
				if ((this._Ngaydat != value))
				{
					this.OnNgaydatChanging(value);
					this.SendPropertyChanging();
					this._Ngaydat = value;
					this.SendPropertyChanged("Ngaydat");
					this.OnNgaydatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaygiao", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaygiao
		{
			get
			{
				return this._Ngaygiao;
			}
			set
			{
				if ((this._Ngaygiao != value))
				{
					this.OnNgaygiaoChanging(value);
					this.SendPropertyChanging();
					this._Ngaygiao = value;
					this.SendPropertyChanged("Ngaygiao");
					this.OnNgaygiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKH", DbType="Int")]
		public System.Nullable<int> IDKH
		{
			get
			{
				return this._IDKH;
			}
			set
			{
				if ((this._IDKH != value))
				{
					if (this._KH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDKHChanging(value);
					this.SendPropertyChanging();
					this._IDKH = value;
					this.SendPropertyChanged("IDKH");
					this.OnIDKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tongtien", DbType="Money")]
		public System.Nullable<decimal> Tongtien
		{
			get
			{
				return this._Tongtien;
			}
			set
			{
				if ((this._Tongtien != value))
				{
					this.OnTongtienChanging(value);
					this.SendPropertyChanging();
					this._Tongtien = value;
					this.SendPropertyChanged("Tongtien");
					this.OnTongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONDATHANG_CHITIETDONTHANG", Storage="_CHITIETDONTHANGs", ThisKey="MaDonHang", OtherKey="MaDonHang")]
		public EntitySet<CHITIETDONTHANG> CHITIETDONTHANGs
		{
			get
			{
				return this._CHITIETDONTHANGs;
			}
			set
			{
				this._CHITIETDONTHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KH_DONDATHANG", Storage="_KH", ThisKey="IDKH", OtherKey="IDKH", IsForeignKey=true)]
		public KH KH
		{
			get
			{
				return this._KH.Entity;
			}
			set
			{
				KH previousValue = this._KH.Entity;
				if (((previousValue != value) 
							|| (this._KH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KH.Entity = null;
						previousValue.DONDATHANGs.Remove(this);
					}
					this._KH.Entity = value;
					if ((value != null))
					{
						value.DONDATHANGs.Add(this);
						this._IDKH = value.IDKH;
					}
					else
					{
						this._IDKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONTHANGs(CHITIETDONTHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONDATHANG = this;
		}
		
		private void detach_CHITIETDONTHANGs(CHITIETDONTHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONDATHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KH")]
	public partial class KH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDKH;
		
		private string _HoTenKH;
		
		private string _TaikhoanKH;
		
		private string _MatkhauKH;
		
		private string _EmailKH;
		
		private string _DiachiKH;
		
		private string _DienthoaiKH;
		
		private System.Nullable<System.DateTime> _NgaysinhKH;
		
		private EntitySet<DONDATHANG> _DONDATHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDKHChanging(int value);
    partial void OnIDKHChanged();
    partial void OnHoTenKHChanging(string value);
    partial void OnHoTenKHChanged();
    partial void OnTaikhoanKHChanging(string value);
    partial void OnTaikhoanKHChanged();
    partial void OnMatkhauKHChanging(string value);
    partial void OnMatkhauKHChanged();
    partial void OnEmailKHChanging(string value);
    partial void OnEmailKHChanged();
    partial void OnDiachiKHChanging(string value);
    partial void OnDiachiKHChanged();
    partial void OnDienthoaiKHChanging(string value);
    partial void OnDienthoaiKHChanged();
    partial void OnNgaysinhKHChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhKHChanged();
    #endregion
		
		public KH()
		{
			this._DONDATHANGs = new EntitySet<DONDATHANG>(new Action<DONDATHANG>(this.attach_DONDATHANGs), new Action<DONDATHANG>(this.detach_DONDATHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDKH
		{
			get
			{
				return this._IDKH;
			}
			set
			{
				if ((this._IDKH != value))
				{
					this.OnIDKHChanging(value);
					this.SendPropertyChanging();
					this._IDKH = value;
					this.SendPropertyChanged("IDKH");
					this.OnIDKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTenKH
		{
			get
			{
				return this._HoTenKH;
			}
			set
			{
				if ((this._HoTenKH != value))
				{
					this.OnHoTenKHChanging(value);
					this.SendPropertyChanging();
					this._HoTenKH = value;
					this.SendPropertyChanged("HoTenKH");
					this.OnHoTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaikhoanKH", DbType="VarChar(50)")]
		public string TaikhoanKH
		{
			get
			{
				return this._TaikhoanKH;
			}
			set
			{
				if ((this._TaikhoanKH != value))
				{
					this.OnTaikhoanKHChanging(value);
					this.SendPropertyChanging();
					this._TaikhoanKH = value;
					this.SendPropertyChanged("TaikhoanKH");
					this.OnTaikhoanKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatkhauKH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatkhauKH
		{
			get
			{
				return this._MatkhauKH;
			}
			set
			{
				if ((this._MatkhauKH != value))
				{
					this.OnMatkhauKHChanging(value);
					this.SendPropertyChanging();
					this._MatkhauKH = value;
					this.SendPropertyChanged("MatkhauKH");
					this.OnMatkhauKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailKH", DbType="VarChar(100)")]
		public string EmailKH
		{
			get
			{
				return this._EmailKH;
			}
			set
			{
				if ((this._EmailKH != value))
				{
					this.OnEmailKHChanging(value);
					this.SendPropertyChanging();
					this._EmailKH = value;
					this.SendPropertyChanged("EmailKH");
					this.OnEmailKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiachiKH", DbType="NVarChar(100)")]
		public string DiachiKH
		{
			get
			{
				return this._DiachiKH;
			}
			set
			{
				if ((this._DiachiKH != value))
				{
					this.OnDiachiKHChanging(value);
					this.SendPropertyChanging();
					this._DiachiKH = value;
					this.SendPropertyChanged("DiachiKH");
					this.OnDiachiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienthoaiKH", DbType="VarChar(15)")]
		public string DienthoaiKH
		{
			get
			{
				return this._DienthoaiKH;
			}
			set
			{
				if ((this._DienthoaiKH != value))
				{
					this.OnDienthoaiKHChanging(value);
					this.SendPropertyChanging();
					this._DienthoaiKH = value;
					this.SendPropertyChanged("DienthoaiKH");
					this.OnDienthoaiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaysinhKH", DbType="Date")]
		public System.Nullable<System.DateTime> NgaysinhKH
		{
			get
			{
				return this._NgaysinhKH;
			}
			set
			{
				if ((this._NgaysinhKH != value))
				{
					this.OnNgaysinhKHChanging(value);
					this.SendPropertyChanging();
					this._NgaysinhKH = value;
					this.SendPropertyChanged("NgaysinhKH");
					this.OnNgaysinhKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KH_DONDATHANG", Storage="_DONDATHANGs", ThisKey="IDKH", OtherKey="IDKH")]
		public EntitySet<DONDATHANG> DONDATHANGs
		{
			get
			{
				return this._DONDATHANGs;
			}
			set
			{
				this._DONDATHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DONDATHANGs(DONDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.KH = this;
		}
		
		private void detach_DONDATHANGs(DONDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.KH = null;
		}
	}
}
#pragma warning restore 1591
